import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About TokenRadar — Methodology & Data Sources",
  description:
    "Learn how TokenRadar calculates Risk Scores, Growth Indexes, and analyzes 250+ crypto tokens using real CoinGecko data and AI-powered research.",
  alternates: {
    canonical: "/about",
  },
  openGraph: {
    title: "About TokenRadar — Methodology & Data Sources",
    description:
      "Learn how TokenRadar calculates Risk Scores, Growth Indexes, and analyzes 250+ crypto tokens using real CoinGecko data and AI-powered research.",
  },
  twitter: {
    title: "About TokenRadar — Methodology & Data Sources",
    description:
      "Learn how TokenRadar calculates Risk Scores, Growth Indexes, and analyzes 250+ crypto tokens using real CoinGecko data and AI-powered research.",
  },
};

/**
 * About page — E-E-A-T signals page explaining methodology,
 * data sources, and the team behind TokenRadar.
 */
export default function AboutPage() {
  return (
    <div className="container">
      <section className="section">
        <div className="article-content">
          <h1>
            About <span className="gradient-text">TokenRadar</span>
          </h1>
          <p style={{ fontSize: "var(--text-lg)", marginTop: "var(--space-lg)" }}>
            TokenRadar is an independent crypto research platform that provides
            unbiased, data-driven analysis for the top 250 cryptocurrency tokens
            by market capitalization.
          </p>

          <h2 id="methodology">Our Methodology</h2>
          <p>
            Every piece of analysis on TokenRadar is built on verified, real-time
            data — never opinions. Here&apos;s how our proprietary metrics work:
          </p>

          <h3>Risk Score (1–10)</h3>
          <p>
            Computed from four factors: <strong>price volatility</strong> (30-day
            standard deviation), <strong>market capitalization</strong> (higher
            cap = lower risk), <strong>token age</strong> (older = more
            established), and <strong>liquidity depth</strong> (24h trading
            volume relative to market cap). A score of 1 means very low risk; 10
            means extremely high risk.
          </p>

          <h3>Growth Potential Index</h3>
          <p>
            Compares a token&apos;s current market cap against the average market cap
            of peers in the same category (DeFi, Layer 2, AI, etc.). Tokens
            significantly below the category average have higher growth
            potential scores.
          </p>

          <h3>Narrative Strength</h3>
          <p>
            Measures the momentum of a token&apos;s category narrative using search
            trend data and social media activity. Categories like AI and RWA
            currently score highest.
          </p>

          <h3>Value vs ATH</h3>
          <p>
            Simply shows the current price as a percentage of the all-time high,
            giving investors a quick view of how far a token is from its peak.
          </p>

          <h2>Data Sources</h2>
          <p>
            All market data is sourced from the{" "}
            <strong>CoinGecko API</strong> and refreshed every 24 hours. We cite
            the exact data timestamp on every article page. Reference analysis
            angles are drawn from reputable outlets like CoinDesk, The Block, and
            Decrypt — we never copy content, only use factual data points.
          </p>

          <h2>AI Content Generation</h2>
          <p>
            Articles are generated by AI using structured prompts that include
            verified CoinGecko data, computed proprietary metrics, and reference
            facts. Every article goes through automated quality checks to ensure
            factual accuracy, proper disclaimers, and no prohibited financial
            advice.
          </p>

          <h2>Contact</h2>
          <p>
            Have questions, feedback, or partnership inquiries? Reach out at{" "}
            <a
              href="mailto:contact@tokenradar.co"
              style={{ color: "var(--accent-secondary)" }}
            >
              contact@tokenradar.co
            </a>
            .
          </p>
        </div>
      </section>
    </div>
  );
}
