import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";
import { describe, expect, it } from "vitest";

const WORKFLOW_DIR = path.join(process.cwd(), ".github", "workflows");
const GENERATED_PR_ACTION_DIR = path.join(
  process.cwd(),
  ".github",
  "actions",
  "publish-generated-pr",
);
const AUTOMATION_WORKFLOWS = [
  "social-automations.yml",
  "daily-content-generation.yml",
  "daily-refresh.yml",
  "deploy.yml",
  "video-assets-refresh.yml",
  "performance.yml",
  "dependency-security.yml",
];

function readWorkflow(name: string): string {
  return fs.readFileSync(path.join(WORKFLOW_DIR, name), "utf-8");
}

function readYaml(filePath: string): unknown {
  const result = spawnSync(
    process.execPath,
    [
      "-e",
      "const fs=require('fs');const yaml=require('js-yaml');process.stdout.write(JSON.stringify(yaml.load(fs.readFileSync(process.argv[1],'utf8'))));",
      filePath,
    ],
    {
      cwd: process.cwd(),
      encoding: "utf-8",
    },
  );

  expect(result.status, result.stderr).toBe(0);
  return JSON.parse(result.stdout) as unknown;
}

function gitLsFiles(pathspec: string): string[] {
  const result = spawnSync("git", ["-c", "safe.directory=D:/tokenradar", "ls-files", pathspec], {
    cwd: process.cwd(),
    encoding: "utf-8",
  });

  expect(result.status).toBe(0);
  return result.stdout.split(/\r?\n/).filter(Boolean);
}

describe("automation runbook contract", () => {
  it("keeps documented workflow-level Telegram fallback alerts wired for every workflow", () => {
    expect(AUTOMATION_WORKFLOWS).toHaveLength(7);

    for (const workflowName of AUTOMATION_WORKFLOWS) {
      const workflow = readWorkflow(workflowName);

      expect(workflow, `${workflowName} is missing a fallback notification step`).toContain("Notify on Failure");
      expect(workflow, `${workflowName} should guard missing report bot token`).toContain("TELEGRAM_REPORT_BOT_TOKEN");
      expect(workflow, `${workflowName} should guard missing report chat id`).toContain("TELEGRAM_REPORT_CHAT_ID");
      expect(workflow, `${workflowName} should call Telegram Bot API`).toContain("https://api.telegram.org/bot$TELEGRAM_REPORT_BOT_TOKEN/sendMessage");
    }
  });

  it("keeps short-retention diagnostics artifacts wired for every workflow", () => {
    for (const workflowName of AUTOMATION_WORKFLOWS) {
      const workflow = readWorkflow(workflowName);

      expect(workflow, `${workflowName} should upload diagnostic artifacts`).toContain("actions/upload-artifact");
      expect(workflow, `${workflowName} diagnostic artifacts should be short-retention`).toContain("retention-days:");
    }
  });

  it("commits every tracked runtime artifact regenerated by the publication build gate", () => {
    const workflow = readWorkflow("daily-content-generation.yml");

    for (const artifact of [
      "data/search-intent.json",
      "data/search-intent-history.json",
      "data/_tokens_blob.json",
      "data/_metrics_blob.json",
      "data/_prices_blob.json",
      "data/_registry.json",
      "public/og/movers.png",
      "public/sitemap.xml",
      "public/sitemap-main.xml",
      "public/sitemap-tokens.xml",
    ]) {
      expect(workflow, `daily-content-generation.yml should stage ${artifact}`).toContain(artifact);
    }
  });

  it("limits publication repair work to token folders changed by the queue publisher", () => {
    const workflow = readWorkflow("daily-content-generation.yml");

    expect(workflow).toContain("Identify published token changes");
    expect(workflow).toContain("data/logs/published-token-ids.txt");
    expect(workflow).toContain('inject-internal-links.ts --token "$token_id"');
    expect(workflow).toContain('repair-article-content.ts --token "$token_id"');
    expect(workflow).toContain("if: steps.published.outputs.count != '0'");
  });

  it("persists the CoinGecko monthly quota counter without restoring broad cache state in social runs", () => {
    const counterWorkflows = [
      readWorkflow("daily-content-generation.yml"),
      readWorkflow("daily-refresh.yml"),
      readWorkflow("social-automations.yml"),
    ];

    for (const workflow of counterWorkflows) {
      expect(workflow).toContain("actions/cache/restore@");
      expect(workflow).toContain("actions/cache/save@");
      expect(workflow).toContain("data/cache/api-counter.json");
      expect(workflow).toContain("coingecko-api-counter-");
      expect(workflow).toContain("group: coingecko-api-counter");
      expect(workflow).toContain("cancel-in-progress: false");
      expect(workflow).toContain("queue: max");
    }

    expect(readWorkflow("daily-content-generation.yml")).toContain("!data/cache/api-counter.json");
    expect(readWorkflow("daily-refresh.yml")).toContain("!data/cache/api-counter.json");
    expect(readWorkflow("social-automations.yml")).not.toContain("name: Cache data/cache");
  });

  it("keeps token OG images as deploy-only generated artifacts", () => {
    const packageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), "package.json"), "utf-8")) as {
      scripts?: Record<string, string>;
    };
    const gitignore = fs.readFileSync(path.join(process.cwd(), ".gitignore"), "utf-8");

    expect(packageJson.scripts?.prebuild).toContain("tsx scripts/generate-og-images.tsx");
    expect(gitignore).toContain("public/og/token/*.png");
    expect(gitLsFiles("public/og/token")).toEqual([]);
    expect(readWorkflow("daily-content-generation.yml")).not.toContain("public/og/token");
    expect(readWorkflow("daily-refresh.yml")).not.toContain("public/og/token");
  });

  it("runs comprehensive checks for pull requests", () => {
    const workflow = readWorkflow("ci.yml");

    expect(workflow).toContain("pull_request:");
    expect(workflow).toContain("npx tsc --noEmit");
    expect(workflow).toContain("npm run lint");
    expect(workflow).toContain("npm run test");
    expect(workflow).toContain("npm run build");
    expect(workflow).toContain("npm run seo:qa");
  });

  it("routes generated publications through an exact-SHA CI-gated pull request", () => {
    const ciWorkflow = readWorkflow("ci.yml");
    const parsedCi = readYaml(path.join(WORKFLOW_DIR, "ci.yml")) as {
      on: {
        pull_request: {
          branches: string[];
        };
        workflow_dispatch: {
          inputs: Record<string, { required: boolean; type: string }>;
        };
      };
      jobs: Record<
        string,
        {
          name: string;
          steps: Array<{
            name?: string;
            if?: string;
            uses?: string;
            env?: Record<string, string>;
            run?: string;
            with?: Record<string, unknown>;
          }>;
        }
      >;
    };
    const actionMetadata = readYaml(
      path.join(GENERATED_PR_ACTION_DIR, "action.yml"),
    ) as {
      inputs: Record<string, { required: boolean }>;
      outputs: Record<string, { value: string }>;
      runs: {
        using: string;
        steps: Array<{
          id?: string;
          env?: Record<string, string>;
          run?: string;
        }>;
      };
    };
    const publisherAction = fs.readFileSync(
      path.join(GENERATED_PR_ACTION_DIR, "publish.sh"),
      "utf-8",
    );

    expect(ciWorkflow).toContain("expected_sha:");
    expect(ciWorkflow).toContain('"$EXPECTED_SHA" != "$GITHUB_SHA"');
    expect(parsedCi.on.workflow_dispatch.inputs.expected_sha).toEqual({
      description: "Exact commit SHA expected for this CI run",
      required: true,
      type: "string",
    });
    expect(parsedCi.on.pull_request.branches).toEqual(["main"]);
    expect(parsedCi.on).not.toHaveProperty("merge_group");
    const ciJob = parsedCi.jobs["required-checks"];
    expect(ciJob.name).toBe("Required checks");
    const expectedShaStep = ciJob.steps.find((step) => step.name === "Validate expected commit SHA");
    const checkoutStep = ciJob.steps.find((step) => step.name === "Checkout code");
    expect(expectedShaStep?.if).toBe("github.event_name == 'workflow_dispatch'");
    expect(expectedShaStep?.env?.EXPECTED_SHA).toBe("${{ inputs.expected_sha }}");
    expect(expectedShaStep?.run).toContain("^[0-9a-f]{40}$");
    expect(expectedShaStep?.run).toContain('"$EXPECTED_SHA" != "$GITHUB_SHA"');
    expect(checkoutStep?.uses).toMatch(/^actions\/checkout@[0-9a-f]{40}$/);
    expect(checkoutStep?.with?.ref).toBeUndefined();
    expect(checkoutStep?.with?.["persist-credentials"]).toBe(false);
    expect(ciJob.steps.indexOf(expectedShaStep!)).toBeLessThan(ciJob.steps.indexOf(checkoutStep!));

    expect(Object.keys(actionMetadata.inputs).sort()).toEqual(
      ["base-sha", "body", "branch", "head-sha", "title", "token"].sort(),
    );
    for (const input of Object.values(actionMetadata.inputs)) {
      expect(input.required).toBe(true);
    }
    expect(actionMetadata.outputs["merge-sha"].value).toBe(
      "${{ steps.publish.outputs.merge_sha }}",
    );
    expect(actionMetadata.outputs["pr-number"].value).toBe(
      "${{ steps.publish.outputs.pr_number }}",
    );
    expect(actionMetadata.outputs["ci-run-id"].value).toBe(
      "${{ steps.publish.outputs.ci_run_id }}",
    );
    expect(actionMetadata.runs.using).toBe("composite");
    const publishStep = actionMetadata.runs.steps.find((step) => step.id === "publish");
    expect(publishStep?.env).toMatchObject({
      GH_TOKEN: "${{ inputs.token }}",
      AUTOMATION_BRANCH: "${{ inputs.branch }}",
      BASE_SHA: "${{ inputs.base-sha }}",
      HEAD_SHA: "${{ inputs.head-sha }}",
      PR_TITLE: "${{ inputs.title }}",
      PR_BODY: "${{ inputs.body }}",
    });
    expect(publishStep?.run).toBe('bash "$GITHUB_ACTION_PATH/publish.sh"');

    for (const workflowName of ["daily-content-generation.yml", "daily-refresh.yml"]) {
      const workflow = readWorkflow(workflowName);
      const parsedWorkflow = readYaml(path.join(WORKFLOW_DIR, workflowName)) as {
        concurrency: {
          group: string;
          "cancel-in-progress": boolean;
          queue: string;
        };
        jobs: Record<
          string,
          {
            if?: string;
            permissions?: Record<string, string>;
            outputs?: Record<string, string>;
            steps?: Array<{
              name?: string;
              id?: string;
              uses?: string;
              with?: Record<string, unknown>;
            }>;
            with?: Record<string, unknown>;
          }
        >;
      };

      expect(workflow).not.toMatch(
        /git push[^\n]*\borigin\s+["']?HEAD:(?:refs\/heads\/)?main["']?/,
      );
      expect(workflow).toContain('git push origin "HEAD:refs/heads/${branch}"');
      expect(workflow).toContain("uses: ./.github/actions/publish-generated-pr");
      expect(workflow).toContain("actions: write");
      expect(workflow).toContain("[skip ci]");
      expect(workflow).toContain("pull-requests: write");
      expect(workflow.match(/statuses: write/g)).toHaveLength(1);
      expect(workflow).toContain("base-sha:");
      expect(workflow).toContain("head-sha:");
      expect(workflow).toContain("needs.integrate.outputs.merge_sha");

      expect(parsedWorkflow.concurrency).toEqual({
        group: "generated-main-publication",
        "cancel-in-progress": false,
        queue: "max",
      });

      expect(parsedWorkflow.jobs.integrate.outputs).toEqual({
        merge_sha: "${{ steps.publish-generated-pr.outputs.merge-sha }}",
        pr_number: "${{ steps.publish-generated-pr.outputs.pr-number }}",
        ci_run_id: "${{ steps.publish-generated-pr.outputs.ci-run-id }}",
      });
      expect(parsedWorkflow.jobs.integrate.permissions).toEqual({
        actions: "write",
        contents: "write",
        "pull-requests": "write",
        statuses: "write",
      });
      const trustedCheckout = parsedWorkflow.jobs.integrate.steps?.find(
        (step) => step.name === "Checkout trusted main",
      );
      expect(trustedCheckout?.uses).toMatch(/^actions\/checkout@[0-9a-f]{40}$/);
      const generatorJobName = workflowName === "daily-refresh.yml" ? "refresh" : "publish";
      expect(trustedCheckout?.with).toEqual({
        ref: `\${{ needs.${generatorJobName}.outputs.base_sha }}`,
        "persist-credentials": false,
      });
      const integrateStep = parsedWorkflow.jobs.integrate.steps?.find(
        (step) => step.id === "publish-generated-pr",
      );
      expect(integrateStep?.uses).toBe("./.github/actions/publish-generated-pr");
      expect(integrateStep?.with).toMatchObject({
        token: "${{ github.token }}",
        branch: `\${{ needs.${generatorJobName}.outputs.branch }}`,
        "base-sha": `\${{ needs.${generatorJobName}.outputs.base_sha }}`,
        "head-sha": `\${{ needs.${generatorJobName}.outputs.head_sha }}`,
      });
      expect(integrateStep?.with?.title).toMatch(/^chore: publish daily /);
      expect(integrateStep?.with?.body).toContain("Source run:");
      expect(parsedWorkflow.jobs.deploy.if).toBe("needs.integrate.outputs.merge_sha != ''");
      expect(parsedWorkflow.jobs.deploy.with?.ref).toBe(
        "${{ needs.integrate.outputs.merge_sha }}",
      );
      expect(parsedWorkflow.jobs.deploy.with?.allow_sha_ref).toBe(true);
    }

    expect(publisherAction).toContain("is_allowed_path");
    expect(publisherAction).toContain("git diff --name-only --no-renames -z");
    expect(publisherAction).toContain("Generated automation may not delete tracked files");
    expect(publisherAction).toContain("require_main_ruleset");
    const rulesetGateIndex = publisherAction.indexOf("\nrequire_main_ruleset\n");
    expect(rulesetGateIndex).toBeGreaterThan(publisherAction.indexOf("repo_owner="));
    expect(rulesetGateIndex).toBeLessThan(publisherAction.indexOf("pulls_json="));
    expect(publisherAction).toContain('all(.[]; .type != "merge_queue")');
    expect(publisherAction).toContain('.context == "Required checks" and .integration_id == 15368');
    expect(publisherAction).toContain("actions/workflows/ci.yml/runs");
    expect(publisherAction).toContain("actions/workflows/ci.yml/dispatches");
    expect(publisherAction).not.toContain("/check-runs");
    expect(publisherAction).toContain("workflow_run_id");
    expect(publisherAction).toContain('gh run watch "$ci_run_id"');
    expect(publisherAction).toContain('ci_run_id="$(find_successful_attested_ci_run)"');
    expect(publisherAction).toContain(
      'verify_ci_run "$candidate_run_id" && verify_required_status "$candidate_run_id"',
    );
    expect(publisherAction).toContain('(.head_sha == $head)');
    expect(publisherAction).toContain('"repos/${GITHUB_REPOSITORY}/statuses/${HEAD_SHA}"');
    expect(publisherAction).toContain('"repos/${GITHUB_REPOSITORY}/commits/${HEAD_SHA}/statuses"');
    expect(publisherAction).toContain('state: "success"');
    expect(publisherAction).toContain('context: "Required checks"');
    expect(publisherAction).toContain('(.creator.login == "github-actions[bot]")');
    const canonicalMergedPrReloadIndex = publisherAction.indexOf(
      "# Collection responses can lag behind the canonical pull-request resource.",
    );
    const canonicalMergedPrBlockEnd = publisherAction.indexOf(
      '\ncurrent_main="$(gh api',
      canonicalMergedPrReloadIndex,
    );
    const canonicalMergedPrBlock = publisherAction.slice(
      canonicalMergedPrReloadIndex,
      canonicalMergedPrBlockEnd,
    );
    expect(canonicalMergedPrReloadIndex).toBeGreaterThan(-1);
    expect(canonicalMergedPrBlockEnd).toBeGreaterThan(canonicalMergedPrReloadIndex);
    expect(canonicalMergedPrBlock).toContain(
      '"repos/${GITHUB_REPOSITORY}/pulls/${pr_number}"',
    );
    expect(canonicalMergedPrBlock).toContain('(.number == $number)');
    expect(canonicalMergedPrBlock).toContain('((.state == "open") or (.state == "closed"))');
    expect(canonicalMergedPrBlock).toContain('((.merged == true) or (.merged == false))');
    expect(canonicalMergedPrBlock).toContain('(.head.ref == $branch)');
    expect(canonicalMergedPrBlock).toContain('(.head.sha == $head)');
    expect(canonicalMergedPrBlock).toContain('(.base.ref == "main")');
    expect(canonicalMergedPrBlock).toContain('(.base.sha == $base)');
    expect(publisherAction).not.toContain(".merge_commit_sha");
    expect(publisherAction).not.toContain("has no valid merge commit SHA");
    expect(publisherAction).toContain("wait_for_main_after_recorded_base() {");
    expect(publisherAction).toContain(
      'existing_merge_sha="$(wait_for_main_after_recorded_base)"',
    );
    const watchIndex = publisherAction.indexOf('gh run watch "$ci_run_id"');
    const verifiedRunIndex = publisherAction.indexOf('verify_ci_run "$ci_run_id"', watchIndex);
    const refreshedMainIndex = publisherAction.indexOf('current_main="$(gh api', verifiedRunIndex);
    const refreshedPrIndex = publisherAction.indexOf('fresh_pr_json="$(gh api', refreshedMainIndex);
    const publishStatusIndex = publisherAction.indexOf(
      '\npublish_required_status "$ci_run_id"\n',
      refreshedPrIndex,
    );
    const mergePayloadIndex = publisherAction.indexOf('merge_payload="$(jq', publishStatusIndex);
    expect(watchIndex).toBeGreaterThan(-1);
    expect(verifiedRunIndex).toBeGreaterThan(watchIndex);
    expect(refreshedMainIndex).toBeGreaterThan(verifiedRunIndex);
    expect(refreshedPrIndex).toBeGreaterThan(refreshedMainIndex);
    expect(publishStatusIndex).toBeGreaterThan(refreshedPrIndex);
    expect(mergePayloadIndex).toBeGreaterThan(publishStatusIndex);
    expect(publisherAction).toContain('merge_method: "squash"');
    const mergeStateHelperIndex = publisherAction.indexOf("\nwait_for_main_at_merge() {");
    const mergeStateHelperEnd = publisherAction.indexOf(
      '\n[[ -n "${GH_TOKEN:-}" ]]',
      mergeStateHelperIndex,
    );
    const mergeStateHelper = publisherAction.slice(mergeStateHelperIndex, mergeStateHelperEnd);
    expect(mergeStateHelperIndex).toBeGreaterThan(-1);
    expect(mergeStateHelperEnd).toBeGreaterThan(mergeStateHelperIndex);
    expect(mergeStateHelper).toContain("for attempt in $(seq 1 30)");
    expect(mergeStateHelper).toContain('"repos/${GITHUB_REPOSITORY}/git/ref/heads/main"');
    expect(mergeStateHelper).toContain('[[ "$current_main" == "$merge_sha" ]]');
    expect(mergeStateHelper).toContain('[[ "$current_main" == "$BASE_SHA" ]]');
    expect(mergeStateHelper).toContain("sleep 2");
    expect(mergeStateHelper).toContain('fail "main did not advance from ${BASE_SHA}');
    expect(mergeStateHelper).not.toContain("/pulls/${pr_number}");
    const mergeShaValidationIndex = publisherAction.indexOf(
      '[[ "$merge_sha" =~ ^[0-9a-f]{40}$ ]]',
      mergePayloadIndex,
    );
    const mergeStateInvocationIndex = publisherAction.indexOf(
      '\nwait_for_main_at_merge "$merge_sha"',
      mergeShaValidationIndex,
    );
    const exactCommitVerificationIndex = publisherAction.indexOf(
      'verify_merge_commit "$merge_sha"',
      mergeStateInvocationIndex,
    );
    expect(mergeStateInvocationIndex).toBeGreaterThan(mergeShaValidationIndex);
    expect(exactCommitVerificationIndex).toBeGreaterThan(mergeStateInvocationIndex);
    expect(publisherAction).toContain('expected_tree="$(git rev-parse "${HEAD_SHA}^{tree}")"');
    expect(publisherAction).toContain('(.tree.sha == $tree)');
    expect(publisherAction).toContain('verify_merge_commit "$existing_merge_sha"');
    expect(publisherAction).toContain('verify_merge_commit "$merge_sha"');
    const idempotentMergeIndex = publisherAction.indexOf(
      '\nif [[ "$pr_merged" == "true" ]]; then',
      publisherAction.indexOf("(( changed_file_count > 0 ))"),
    );
    const idempotentMergeEnd = publisherAction.indexOf(
      '\nif [[ -z "$pr_number" ]]',
      idempotentMergeIndex,
    );
    const idempotentMergeBlock = publisherAction.slice(idempotentMergeIndex, idempotentMergeEnd);
    expect(idempotentMergeIndex).toBeGreaterThan(-1);
    expect(idempotentMergeEnd).toBeGreaterThan(idempotentMergeIndex);
    expect(idempotentMergeBlock.indexOf("delete_automation_branch")).toBeGreaterThan(
      idempotentMergeBlock.indexOf('verify_required_status "$ci_run_id"'),
    );
    expect(idempotentMergeBlock.indexOf('write_outputs "$existing_merge_sha"')).toBeGreaterThan(
      idempotentMergeBlock.indexOf("delete_automation_branch"),
    );
  });

  it("does not publish YouTube fallback video after strict R2 hydration fails", () => {
    const workflow = readWorkflow("social-automations.yml");
    const youtubeStart = workflow.indexOf("- name: YouTube Video Breakout");
    const youtubeEnd = workflow.indexOf("\n      - name:", youtubeStart + 1);
    const youtubeBlock = workflow.slice(youtubeStart, youtubeEnd);

    expect(youtubeStart).toBeGreaterThan(-1);
    expect(youtubeBlock).toContain("steps.install-ffmpeg.outcome == 'success'");
    expect(youtubeBlock).toContain("steps.hydrate-video-assets.outcome == 'success'");
    for (const variable of [
      "R2_ACCOUNT_ID",
      "R2_ACCESS_KEY_ID",
      "R2_SECRET_ACCESS_KEY",
      "R2_BUCKET_NAME",
      "R2_PUBLIC_URL",
    ]) {
      expect(youtubeBlock, `YouTube should receive ${variable} for selected-asset hydration`).toContain(variable);
    }
  });

  it("scopes the optional R2 account metrics token to the usage snapshot step", () => {
    const workflow = readWorkflow("social-automations.yml");
    const snapshotStart = workflow.indexOf("- name: Record Weekly Cloudflare Usage Snapshot");
    const snapshotEnd = workflow.indexOf("\n      - name:", snapshotStart + 1);
    const snapshotBlock = workflow.slice(snapshotStart, snapshotEnd);
    const tokenMapping = "CLOUDFLARE_R2_METRICS_API_TOKEN: ${{ secrets.CLOUDFLARE_R2_METRICS_API_TOKEN }}";

    expect(snapshotStart).toBeGreaterThan(-1);
    expect(snapshotBlock).toContain(tokenMapping);
    expect(workflow.replace(snapshotBlock, "")).not.toContain("CLOUDFLARE_R2_METRICS_API_TOKEN");
  });

  it("allows an R2 deletion preview without weakening confirmed deletion authorization", () => {
    const script = fs.readFileSync(path.join(process.cwd(), "scripts", "prune-video-assets.ts"), "utf-8");
    const deleteFunctionStart = script.indexOf("async function deleteUnreferencedR2Assets");
    const authorizationStart = script.indexOf("  if (!dryRun) {", deleteFunctionStart);
    const listingStart = script.indexOf('  const objectKeys = await listObjectKeys("video-assets/broll/");');
    const authorizationBlock = script.slice(authorizationStart, listingStart);
    const deleteCallStart = script.indexOf("const deleted = await deleteObjects(unreferencedKeys);", listingStart);
    const deleteFunctionEnd = script.indexOf("\n}\n\nasync function main", deleteCallStart);
    const confirmedDeleteBlock = script.slice(deleteCallStart, deleteFunctionEnd);

    expect(deleteFunctionStart).toBeGreaterThan(-1);
    expect(authorizationStart).toBeGreaterThan(deleteFunctionStart);
    expect(listingStart).toBeGreaterThan(authorizationStart);
    expect(authorizationBlock).toContain("if (!confirmed)");
    expect(authorizationBlock).toContain("readFreshHydrationGuard(args);");
    expect(deleteCallStart).toBeGreaterThan(listingStart);
    expect(confirmedDeleteBlock).toContain("fs.rmSync(HYDRATION_GUARD_FILE, { force: true });");
  });

  it("refreshes search-intent artifacts before the daily refresh commit", () => {
    const workflow = readWorkflow("daily-refresh.yml");

    expect(workflow).toContain("npx tsx scripts/compute-search-intent.ts");
    expect(workflow).toContain("data/search-intent.json");
    expect(workflow).toContain("data/search-intent-history.json");
  });

  it("gives the system report durable AI-cost ledger access without leaking it into unrelated steps", () => {
    const workflow = readWorkflow("daily-refresh.yml");
    const workflowEnvBlock = workflow.slice(0, workflow.indexOf("\njobs:"));
    const reportStart = workflow.indexOf("- name: Dispatch System Report & Cleanup");
    const reportEnd = workflow.indexOf("\n      - name:", reportStart + 1);
    const reportBlock = workflow.slice(reportStart, reportEnd);
    const exportStart = workflow.indexOf("- name: Export engagement analytics baseline");
    const exportEnd = workflow.indexOf("\n      - name:", exportStart + 1);
    const exportBlock = workflow.slice(exportStart, exportEnd);
    const referenceStart = workflow.indexOf("- name: Fetch reference articles");
    const referenceEnd = workflow.indexOf("\n      - name:", referenceStart + 1);
    const referenceBlock = workflow.slice(referenceStart, referenceEnd);

    expect(reportStart).toBeGreaterThan(-1);
    expect(reportBlock).toContain("CLOUDFLARE_API_TOKEN");
    expect(reportBlock).toContain("CLOUDFLARE_ACCOUNT_ID");
    expect(workflowEnvBlock).toContain(
      "D1_DATABASE_ID: ${{ vars.D1_DATABASE_ID || secrets.D1_DATABASE_ID }}",
    );
    expect(exportBlock).toContain('SOCIAL_ATTRIBUTION_LEDGER_REQUIRED: "true"');
    expect(referenceBlock).not.toContain("D1_DATABASE_ID");
    expect(workflow).not.toContain("92ac6df2-40b4-4c5a-ad56-68142eefcf36");
    expect(readWorkflow("social-automations.yml"))
      .not.toContain("92ac6df2-40b4-4c5a-ad56-68142eefcf36");
  });

  it("keeps the reduced publishing cadence and measurement routes wired", () => {
    const workflow = readWorkflow("social-automations.yml");

    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform telegram");
    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform x");
    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform telegram --format radar-divergence");
    expect(workflow).toContain("npx tsx scripts/post-token-comparison.ts --platform telegram");
    expect(workflow).toContain("npx tsx scripts/post-token-comparison.ts --platform x");
    expect(workflow).not.toContain("npx tsx scripts/post-token-comparison.ts --platform instagram");
    expect(workflow).not.toContain("--format watchlist-check");
    expect(workflow).not.toContain("--format market-pulse");
    expect(workflow).not.toContain("npx tsx scripts/post-token-comparison.ts --platform meta");
    expect(workflow).toContain("npx tsx scripts/post-daily-poll.ts");
    expect(workflow).not.toContain("npx tsx scripts/post-interactive-daily.ts");
    expect(workflow).toContain("Refresh Market Inputs and Derived Metrics For Price-Sensitive Routes");
    expect(workflow).toContain("npx tsx scripts/post-video-daily.ts --platform x");
    expect(workflow).toContain("npx tsx scripts/post-video-daily.ts --platform instagram");
    expect(workflow).toContain("npx tsx scripts/post-video-daily.ts --platform youtube");
    expect(workflow).not.toContain("npx tsx scripts/post-video-daily.ts --platform tiktok");
    expect(workflow).toContain("github.event.schedule == '43 18 * * 3'");
    expect(workflow).toContain("github.event.schedule == '57 18 * * 1,3,5'");
    expect(workflow).not.toContain("npx tsx scripts/post-video-daily.ts --platform instagram-youtube");
    expect(workflow).not.toContain("npx tsx scripts/post-video-daily.ts --platform all");
    expect(workflow).toContain("npm run social:metrics:collect");
    expect(workflow).toContain("npm run social:metrics:report:file");
    expect(workflow).toContain("github.event.schedule != '53 * * * *'");
    expect(workflow).toContain("github.event.schedule != '31 08 * * 1'");
    expect(workflow).toContain("name: Collect Native Social Metrics");
    expect(workflow).toContain("name: Build Weekly Social Performance Report");
    expect(workflow.indexOf("npx tsx scripts/compute-metrics.ts")).toBeLessThan(
      workflow.indexOf("npx tsx scripts/post-video-daily.ts --platform youtube"),
    );

    const pollStart = workflow.indexOf("id: telegram-poll");
    const pollEnd = workflow.indexOf("\n      - name:", pollStart);
    const pollBlock = workflow.slice(pollStart, pollEnd);
    expect(pollBlock).not.toContain("steps.refresh-social-metrics.outcome");
    expect(workflow).toContain("env.IS_TELEGRAM_POLL_RUN != 'true'");
  });

  it("isolates weekly Meta token maintenance and wires the explicit Instagram auth mode", () => {
    const socialWorkflow = readWorkflow("social-automations.yml");
    const dailyWorkflow = readWorkflow("daily-refresh.yml");

    expect(socialWorkflow).toContain("IG_AUTH_MODE: ${{ vars.IG_AUTH_MODE || 'facebook_login' }}");
    expect(socialWorkflow).toContain("- meta-token-refresh");
    expect(socialWorkflow).toContain("name: Maintain Meta Access Tokens");
    expect(socialWorkflow).toContain("github.event.inputs.run == 'meta-token-refresh'");
    expect(socialWorkflow).toContain("npx tsx scripts/refresh-meta-tokens.ts");
    expect(socialWorkflow).toContain("IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}");
    expect(socialWorkflow).toContain("THREADS_ACCOUNT_ID: ${{ secrets.THREADS_ACCOUNT_ID }}");
    expect(socialWorkflow).not.toContain("THREADS_APP_ID");
    expect(socialWorkflow).not.toContain("THREADS_APP_SECRET");
    expect(socialWorkflow).not.toContain("name: Update Meta OAuth Secrets");
    expect(dailyWorkflow).not.toContain("scripts/refresh-meta-tokens.ts");
  });

  it("keeps social routes failure-isolated, time-bounded, and freshness-gated", () => {
    const workflow = readWorkflow("social-automations.yml");

    expect(workflow).toContain("timeout-minutes: 120");
    expect(workflow).not.toContain("github.event.inputs.run == 'all'");
    expect(workflow).toContain("id: refresh-social-metrics");
    expect(workflow).toContain("Refresh Market Inputs and Derived Metrics For Price-Sensitive Routes");
    expect(workflow).toContain("steps.refresh-social-metrics.outcome == 'success'");
    expect(workflow).toContain("id: aggregate-publishing-routes");
    expect(workflow).toContain("Aggregate publishing route outcomes");
    expect(workflow).toContain("telegram-market=${{ steps.telegram-market.outcome }}");
    expect(workflow).toContain("x-market=${{ steps.x-market.outcome }}");
    expect(workflow).toContain("telegram-poll=${{ steps.telegram-poll.outcome }}");
    expect(workflow).toContain("x-video=${{ steps.x-video.outcome }}");
    expect(workflow).toContain("instagram-reel=${{ steps.instagram-reel.outcome }}");
    expect(workflow).toContain("youtube-video=${{ steps.youtube-video.outcome }}");

    const routeIds = [
      "telegram-market",
      "instagram-carousel",
      "x-comparison",
      "telegram-comparison",
      "telegram-poll",
      "x-market",
      "telegram-movers",
      "telegram-recap",
      "telegram-divergence",
      "threads-text",
      "threads-recap",
      "x-video",
      "instagram-reel",
      "youtube-video",
    ];
    for (const routeId of routeIds) {
      const routeStart = workflow.indexOf(`id: ${routeId}`);
      expect(routeStart, `${routeId} should have a step id`).toBeGreaterThan(-1);
      const routeBlock = workflow.slice(routeStart, routeStart + 300);
      expect(routeBlock, `${routeId} should run after sibling failures`).toContain("if: always()");
      expect(routeBlock, `${routeId} should report its real outcome to the aggregator`).toContain(
        "continue-on-error: true",
      );
      expect(routeBlock, `${routeId} should have a route timeout`).toMatch(/timeout-minutes: \d+/);
    }
  });

  it("repairs and verifies provider-dated inputs before strict social routes publish", () => {
    const socialWorkflow = readWorkflow("social-automations.yml");
    const dailyWorkflow = readWorkflow("daily-refresh.yml");
    const fetcher = fs.readFileSync(path.join(process.cwd(), "scripts", "fetch-crypto-data.ts"), "utf-8");
    const reporter = fs.readFileSync(path.join(process.cwd(), "scripts", "send-system-report.ts"), "utf-8");
    const tokenSelection = fs.readFileSync(
      path.join(process.cwd(), "scripts", "lib", "token-selection.ts"),
      "utf-8",
    );
    const seoWorkflow = readWorkflow("seo-maintenance.yml");
    const seoOpportunities = fs.readFileSync(
      path.join(process.cwd(), "scripts", "generate-seo-opportunities.ts"),
      "utf-8",
    );
    const contentGenerator = fs.readFileSync(
      path.join(process.cwd(), "scripts", "generate-content.ts"),
      "utf-8",
    );

    expect(socialWorkflow).toContain("--full-refresh-order social-rank");
    expect(socialWorkflow).toContain("--full-refresh-min-success 4");
    expect(socialWorkflow).toContain("--full-refresh-rank-limit 250");
    expect(socialWorkflow).toContain("--full-refresh-rank-limit 50");
    expect(socialWorkflow).toContain('readiness_mode="comparison"');
    expect(socialWorkflow).toContain('readiness_mode="video"');
    expect(socialWorkflow).toContain(
      'npx tsx scripts/validate-social-market-readiness.ts --mode "$readiness_mode"',
    );
    expect(dailyWorkflow).toContain("--full-refresh-min-success 1");
    expect(fetcher).toContain("getPriceHistoryObservationAgeMs");
    expect(fetcher).not.toContain("fs.statSync(priceFile).mtimeMs");
    expect(reporter).toContain("getPriceHistoryObservationAgeMs");
    expect(reporter).not.toContain("mtimeMs");
    expect(tokenSelection).not.toContain("fs.statSync(overviewPath)");
    expect(seoWorkflow).toContain("fetch-depth: 0");
    expect(seoOpportunities).toContain("gitCommitDate(staticPath)");
    expect(seoOpportunities).not.toContain("statSync(staticPath).mtime");
    expect(contentGenerator).not.toContain("stats.mtime");
  });

  it("keeps social cron slots away from high-risk hour-boundary minutes", () => {
    const workflow = readWorkflow("social-automations.yml");
    const crons = [...workflow.matchAll(/- cron: "([^"]+)"/g)].map((match) => match[1]);

    expect(crons.length).toBeGreaterThan(0);

    for (const cron of crons) {
      const minute = cron.split(" ")[0];

      expect(minute, `${cron} should avoid minute 00/05`).not.toMatch(/^(00|05)$/);
    }
  });

  it("keeps runner recovery strict when measurement jobs are skipped", () => {
    const workflow = readWorkflow("social-runner-recovery.yml");

    expect(workflow).toContain("group: social-runner-recovery");
    expect(workflow).toContain("cancel-in-progress: false");
    expect(workflow).toContain("queue: max");
    expect(workflow).toContain('select(.conclusion != "skipped")');
    expect(workflow).toContain('.name == "Execute Network Routing"');
    expect(workflow).toContain('"$active_job_count" != "1"');
    expect(workflow).toContain('"$step_count" != "0"');
  });

  it("keeps social schedule routes aligned with declared cron slots", () => {
    const workflow = readWorkflow("social-automations.yml");
    const crons = new Set([...workflow.matchAll(/- cron: "([^"]+)"/g)].map((match) => match[1]));
    const directScheduleRoutes = [...workflow.matchAll(/github\.event\.schedule == '([^']+)'/g)].map((match) => match[1]);
    const arrayScheduleRoutes = [...workflow.matchAll(/fromJson\('(\[[^']+\])'\)/g)].flatMap((match) =>
      JSON.parse(match[1]) as string[],
    );
    const scheduleRoutes = new Set([...directScheduleRoutes, ...arrayScheduleRoutes]);

    expect([...scheduleRoutes].sort()).toEqual([...crons].sort());
  });
});
