import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";
import { describe, expect, it } from "vitest";

const WORKFLOW_DIR = path.join(process.cwd(), ".github", "workflows");
const AUTOMATION_WORKFLOWS = [
  "social-automations.yml",
  "daily-content-generation.yml",
  "daily-refresh.yml",
  "deploy.yml",
  "video-assets-refresh.yml",
  "performance.yml",
  "dependency-security.yml",
];

function readWorkflow(name: string): string {
  return fs.readFileSync(path.join(WORKFLOW_DIR, name), "utf-8");
}

function gitLsFiles(pathspec: string): string[] {
  const result = spawnSync("git", ["-c", "safe.directory=D:/tokenradar", "ls-files", pathspec], {
    cwd: process.cwd(),
    encoding: "utf-8",
  });

  expect(result.status).toBe(0);
  return result.stdout.split(/\r?\n/).filter(Boolean);
}

describe("automation runbook contract", () => {
  it("keeps documented workflow-level Telegram fallback alerts wired for every workflow", () => {
    expect(AUTOMATION_WORKFLOWS).toHaveLength(7);

    for (const workflowName of AUTOMATION_WORKFLOWS) {
      const workflow = readWorkflow(workflowName);

      expect(workflow, `${workflowName} is missing a fallback notification step`).toContain("Notify on Failure");
      expect(workflow, `${workflowName} should guard missing report bot token`).toContain("TELEGRAM_REPORT_BOT_TOKEN");
      expect(workflow, `${workflowName} should guard missing report chat id`).toContain("TELEGRAM_REPORT_CHAT_ID");
      expect(workflow, `${workflowName} should call Telegram Bot API`).toContain("https://api.telegram.org/bot$TELEGRAM_REPORT_BOT_TOKEN/sendMessage");
    }
  });

  it("keeps short-retention diagnostics artifacts wired for every workflow", () => {
    for (const workflowName of AUTOMATION_WORKFLOWS) {
      const workflow = readWorkflow(workflowName);

      expect(workflow, `${workflowName} should upload diagnostic artifacts`).toContain("actions/upload-artifact");
      expect(workflow, `${workflowName} diagnostic artifacts should be short-retention`).toContain("retention-days:");
    }
  });

  it("commits every tracked runtime artifact regenerated by the publication build gate", () => {
    const workflow = readWorkflow("daily-content-generation.yml");

    for (const artifact of [
      "data/search-intent.json",
      "data/search-intent-history.json",
      "data/_tokens_blob.json",
      "data/_metrics_blob.json",
      "data/_prices_blob.json",
      "data/_registry.json",
      "public/og/movers.png",
      "public/sitemap.xml",
      "public/sitemap-main.xml",
      "public/sitemap-tokens.xml",
    ]) {
      expect(workflow, `daily-content-generation.yml should stage ${artifact}`).toContain(artifact);
    }
  });

  it("limits publication repair work to token folders changed by the queue publisher", () => {
    const workflow = readWorkflow("daily-content-generation.yml");

    expect(workflow).toContain("Identify published token changes");
    expect(workflow).toContain("data/logs/published-token-ids.txt");
    expect(workflow).toContain('inject-internal-links.ts --token "$token_id"');
    expect(workflow).toContain('repair-article-content.ts --token "$token_id"');
    expect(workflow).toContain("if: steps.published.outputs.count != '0'");
  });

  it("persists the CoinGecko monthly quota counter without restoring broad cache state in social runs", () => {
    const counterWorkflows = [
      readWorkflow("daily-content-generation.yml"),
      readWorkflow("daily-refresh.yml"),
      readWorkflow("social-automations.yml"),
    ];

    for (const workflow of counterWorkflows) {
      expect(workflow).toContain("actions/cache/restore@");
      expect(workflow).toContain("actions/cache/save@");
      expect(workflow).toContain("data/cache/api-counter.json");
      expect(workflow).toContain("coingecko-api-counter-");
      expect(workflow).toContain("group: coingecko-api-counter");
      expect(workflow).toContain("cancel-in-progress: false");
      expect(workflow).toContain("queue: max");
    }

    expect(readWorkflow("daily-content-generation.yml")).toContain("!data/cache/api-counter.json");
    expect(readWorkflow("daily-refresh.yml")).toContain("!data/cache/api-counter.json");
    expect(readWorkflow("social-automations.yml")).not.toContain("name: Cache data/cache");
  });

  it("keeps token OG images as deploy-only generated artifacts", () => {
    const packageJson = JSON.parse(fs.readFileSync(path.join(process.cwd(), "package.json"), "utf-8")) as {
      scripts?: Record<string, string>;
    };
    const gitignore = fs.readFileSync(path.join(process.cwd(), ".gitignore"), "utf-8");

    expect(packageJson.scripts?.prebuild).toContain("tsx scripts/generate-og-images.tsx");
    expect(gitignore).toContain("public/og/token/*.png");
    expect(gitLsFiles("public/og/token")).toEqual([]);
    expect(readWorkflow("daily-content-generation.yml")).not.toContain("public/og/token");
    expect(readWorkflow("daily-refresh.yml")).not.toContain("public/og/token");
  });

  it("runs comprehensive checks for pull requests and merge queues", () => {
    const workflow = readWorkflow("ci.yml");

    expect(workflow).toContain("pull_request:");
    expect(workflow).toContain("npx tsc --noEmit");
    expect(workflow).toContain("npm run lint");
    expect(workflow).toContain("npm run test");
    expect(workflow).toContain("npm run build");
    expect(workflow).toContain("npm run seo:qa");
  });

  it("does not publish YouTube fallback video after strict R2 hydration fails", () => {
    const workflow = readWorkflow("social-automations.yml");
    const youtubeStart = workflow.indexOf("- name: YouTube Video Breakout");
    const youtubeEnd = workflow.indexOf("\n      - name:", youtubeStart + 1);
    const youtubeBlock = workflow.slice(youtubeStart, youtubeEnd);

    expect(youtubeStart).toBeGreaterThan(-1);
    expect(youtubeBlock).toContain("steps.hydrate-video-assets.outcome == 'success'");
    for (const variable of [
      "R2_ACCOUNT_ID",
      "R2_ACCESS_KEY_ID",
      "R2_SECRET_ACCESS_KEY",
      "R2_BUCKET_NAME",
      "R2_PUBLIC_URL",
    ]) {
      expect(youtubeBlock, `YouTube should receive ${variable} for selected-asset hydration`).toContain(variable);
    }
  });

  it("allows an R2 deletion preview without weakening confirmed deletion authorization", () => {
    const script = fs.readFileSync(path.join(process.cwd(), "scripts", "prune-video-assets.ts"), "utf-8");
    const deleteFunctionStart = script.indexOf("async function deleteUnreferencedR2Assets");
    const authorizationStart = script.indexOf("  if (!dryRun) {", deleteFunctionStart);
    const listingStart = script.indexOf('  const objectKeys = await listObjectKeys("video-assets/broll/");');
    const authorizationBlock = script.slice(authorizationStart, listingStart);
    const deleteCallStart = script.indexOf("const deleted = await deleteObjects(unreferencedKeys);", listingStart);
    const deleteFunctionEnd = script.indexOf("\n}\n\nasync function main", deleteCallStart);
    const confirmedDeleteBlock = script.slice(deleteCallStart, deleteFunctionEnd);

    expect(deleteFunctionStart).toBeGreaterThan(-1);
    expect(authorizationStart).toBeGreaterThan(deleteFunctionStart);
    expect(listingStart).toBeGreaterThan(authorizationStart);
    expect(authorizationBlock).toContain("if (!confirmed)");
    expect(authorizationBlock).toContain("readFreshHydrationGuard(args);");
    expect(deleteCallStart).toBeGreaterThan(listingStart);
    expect(confirmedDeleteBlock).toContain("fs.rmSync(HYDRATION_GUARD_FILE, { force: true });");
  });

  it("refreshes search-intent artifacts before the daily refresh commit", () => {
    const workflow = readWorkflow("daily-refresh.yml");

    expect(workflow).toContain("npx tsx scripts/compute-search-intent.ts");
    expect(workflow).toContain("data/search-intent.json");
    expect(workflow).toContain("data/search-intent-history.json");
  });

  it("gives the system report durable AI-cost ledger access without leaking it into unrelated steps", () => {
    const workflow = readWorkflow("daily-refresh.yml");
    const workflowEnvBlock = workflow.slice(0, workflow.indexOf("\njobs:"));
    const reportStart = workflow.indexOf("- name: Dispatch System Report & Cleanup");
    const reportEnd = workflow.indexOf("\n      - name:", reportStart + 1);
    const reportBlock = workflow.slice(reportStart, reportEnd);
    const exportStart = workflow.indexOf("- name: Export engagement analytics baseline");
    const exportEnd = workflow.indexOf("\n      - name:", exportStart + 1);
    const exportBlock = workflow.slice(exportStart, exportEnd);
    const referenceStart = workflow.indexOf("- name: Fetch reference articles");
    const referenceEnd = workflow.indexOf("\n      - name:", referenceStart + 1);
    const referenceBlock = workflow.slice(referenceStart, referenceEnd);

    expect(reportStart).toBeGreaterThan(-1);
    expect(reportBlock).toContain("CLOUDFLARE_API_TOKEN");
    expect(reportBlock).toContain("CLOUDFLARE_ACCOUNT_ID");
    expect(workflowEnvBlock).toContain(
      "D1_DATABASE_ID: ${{ vars.D1_DATABASE_ID || secrets.D1_DATABASE_ID }}",
    );
    expect(exportBlock).toContain('SOCIAL_ATTRIBUTION_LEDGER_REQUIRED: "true"');
    expect(referenceBlock).not.toContain("D1_DATABASE_ID");
    expect(workflow).not.toContain("92ac6df2-40b4-4c5a-ad56-68142eefcf36");
    expect(readWorkflow("social-automations.yml"))
      .not.toContain("92ac6df2-40b4-4c5a-ad56-68142eefcf36");
  });

  it("keeps the reduced publishing cadence and measurement routes wired", () => {
    const workflow = readWorkflow("social-automations.yml");

    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform telegram");
    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform x");
    expect(workflow).toContain("npx tsx scripts/post-market-updates.ts --platform telegram --format radar-divergence");
    expect(workflow).toContain("npx tsx scripts/post-token-comparison.ts --platform telegram");
    expect(workflow).toContain("npx tsx scripts/post-token-comparison.ts --platform x");
    expect(workflow).toContain("npx tsx scripts/post-token-comparison.ts --platform instagram");
    expect(workflow).not.toContain("--format watchlist-check");
    expect(workflow).not.toContain("--format market-pulse");
    expect(workflow).not.toContain("npx tsx scripts/post-token-comparison.ts --platform meta");
    expect(workflow).not.toContain("npx tsx scripts/post-daily-poll.ts");
    expect(workflow).not.toContain("npx tsx scripts/post-interactive-daily.ts");
    expect(workflow).toContain("Short-form Video Breakout (Mon/Wed/Fri; YouTube only)");
    expect(workflow).toContain("Refresh Market Inputs and Derived Metrics For Price-Sensitive Routes");
    expect(workflow).toContain("npx tsx scripts/post-video-daily.ts --platform youtube");
    expect(workflow).not.toContain("npx tsx scripts/post-video-daily.ts --platform instagram-youtube");
    expect(workflow).not.toContain("npx tsx scripts/post-video-daily.ts --platform all");
    expect(workflow).toContain("npm run social:metrics:collect");
    expect(workflow).toContain("npm run social:metrics:report:file");
    expect(workflow).toContain("github.event.schedule != '53 * * * *'");
    expect(workflow).toContain("github.event.schedule != '31 08 * * 1'");
    expect(workflow).toContain("name: Collect Native Social Metrics");
    expect(workflow).toContain("name: Build Weekly Social Performance Report");
    expect(workflow.indexOf("npx tsx scripts/compute-metrics.ts")).toBeLessThan(
      workflow.indexOf("npx tsx scripts/post-video-daily.ts --platform youtube"),
    );
  });

  it("keeps social routes failure-isolated, time-bounded, and freshness-gated", () => {
    const workflow = readWorkflow("social-automations.yml");

    expect(workflow).toContain("timeout-minutes: 120");
    expect(workflow).not.toContain("github.event.inputs.run == 'all'");
    expect(workflow).toContain("id: refresh-social-metrics");
    expect(workflow).toContain("Refresh Market Inputs and Derived Metrics For Price-Sensitive Routes");
    expect(workflow).toContain("steps.refresh-social-metrics.outcome == 'success'");
    expect(workflow).toContain("id: aggregate-publishing-routes");
    expect(workflow).toContain("Aggregate publishing route outcomes");
    expect(workflow).toContain("telegram-market=${{ steps.telegram-market.outcome }}");
    expect(workflow).toContain("x-market=${{ steps.x-market.outcome }}");
    expect(workflow).toContain("instagram-comparison=${{ steps.instagram-comparison.outcome }}");
    expect(workflow).toContain("youtube-video=${{ steps.youtube-video.outcome }}");

    const routeIds = [
      "telegram-market",
      "instagram-carousel",
      "x-comparison",
      "telegram-comparison",
      "x-market",
      "telegram-movers",
      "telegram-recap",
      "telegram-divergence",
      "threads-text",
      "threads-recap",
      "instagram-comparison",
      "youtube-video",
    ];
    for (const routeId of routeIds) {
      const routeStart = workflow.indexOf(`id: ${routeId}`);
      expect(routeStart, `${routeId} should have a step id`).toBeGreaterThan(-1);
      const routeBlock = workflow.slice(routeStart, routeStart + 300);
      expect(routeBlock, `${routeId} should run after sibling failures`).toContain("if: always()");
      expect(routeBlock, `${routeId} should report its real outcome to the aggregator`).toContain(
        "continue-on-error: true",
      );
      expect(routeBlock, `${routeId} should have a route timeout`).toMatch(/timeout-minutes: \d+/);
    }
  });

  it("keeps social cron slots away from high-risk hour-boundary minutes", () => {
    const workflow = readWorkflow("social-automations.yml");
    const crons = [...workflow.matchAll(/- cron: "([^"]+)"/g)].map((match) => match[1]);

    expect(crons.length).toBeGreaterThan(0);

    for (const cron of crons) {
      const minute = cron.split(" ")[0];

      expect(minute, `${cron} should avoid minute 00/05`).not.toMatch(/^(00|05)$/);
    }
  });

  it("keeps runner recovery strict when measurement jobs are skipped", () => {
    const workflow = readWorkflow("social-runner-recovery.yml");

    expect(workflow).toContain('select(.conclusion != "skipped")');
    expect(workflow).toContain('.name == "Execute Network Routing"');
    expect(workflow).toContain('"$active_job_count" != "1"');
    expect(workflow).toContain('"$step_count" != "0"');
  });

  it("keeps social schedule routes aligned with declared cron slots", () => {
    const workflow = readWorkflow("social-automations.yml");
    const crons = new Set([...workflow.matchAll(/- cron: "([^"]+)"/g)].map((match) => match[1]));
    const directScheduleRoutes = [...workflow.matchAll(/github\.event\.schedule == '([^']+)'/g)].map((match) => match[1]);
    const arrayScheduleRoutes = [...workflow.matchAll(/fromJson\('(\[[^']+\])'\)/g)].flatMap((match) =>
      JSON.parse(match[1]) as string[],
    );
    const scheduleRoutes = new Set([...directScheduleRoutes, ...arrayScheduleRoutes]);

    expect([...scheduleRoutes].sort()).toEqual([...crons].sort());
  });
});
